### ISSUE TITLE
How to download pdf

### ISSUE THREAD

**Issue by alfa-dot** [adityathakurxd/flutterfire_pdfs#1]
How do i set on Pressed function when i want to download pdf

Thanks.

**Comment by adityathakurxd** [comment]
To download pdf to your device, the onPressed can look something like this:
```dart
onPressed: (){
        downloadFileExample();
      },
```
Where the `downloadFileExample()` is defined as:
```dart
  import 'package:path_provider/path_provider.dart';

  Future<void> downloadFileExample() async {
    Directory appDocDir = await getApplicationDocumentsDirectory();
    File downloadToFile = File('${appDocDir.path}/download-file.pdf');

    try {
      await firebase_storage.FirebaseStorage.instance
          .ref('uploads/filename.pdf')
          .writeToFile(downloadToFile);
    } on firebase_core.FirebaseException catch (e) {
      // e.g, e.code == 'canceled'
    }
  }
```

**Note:**  We call the `writeToFile` method on any storage bucket reference to download a file to the local device.

You can refer to [FlutterFire documentation](https://firebase.flutter.dev/docs/storage/usage#downloading-files) on downloading files for more details. 
If you're satisfied with the answer, please close this issue. Thank you.

**Comment by alfa-dot** [comment]
Thanks man, what if i have multiple file to download or i want to download
from url?

Sorry, i'm a new developer

Thanks.

**Comment by alfa-dot** [comment]
For example, if i want to download from my collection using given url from
my database below:


  url.PNG
<https://drive.google.com/file/d/1mH1KxpU6rljhcbLo7XpkWzC-aizPNDJM/view?usp=drivesdk>

How can i achieve that, thanks.
